import os
import json

# Paths
PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DB_PATH = os.path.join(PROJECT_ROOT, 'androidApp', 'src', 'main', 'assets', 'plants.db')
CACHE_DIR = os.path.join(os.path.dirname(__file__), 'cache')
IMAGE_CACHE_DIR = os.path.join(CACHE_DIR, 'images')
PROGRESS_FILE = os.path.join(os.path.dirname(__file__), 'progress.json')

# Ensure cache directories exist
os.makedirs(IMAGE_CACHE_DIR, exist_ok=True)

# API Configuration
# POWO uses pykew library (official client)
WIKIPEDIA_API_BASE = "https://en.wikipedia.org/w/api.php"
GBIF_API_BASE = "https://api.gbif.org/v1/species/match"
COMMONS_API_BASE = "https://commons.wikimedia.org/w/api.php"

# Languages (in search/population order)
LANGUAGES = ['en', 'ro', 'es', 'de', 'fr', 'it', 'ru', 'pt', 'zh', 'ja', 'ar', 'hi']
LANGUAGE_CODES = {
    'en': 'en',
    'ro': 'ro',
    'es': 'es',
    'de': 'de',
    'fr': 'fr',
    'it': 'it',
    'ru': 'ru',
    'pt': 'pt',
    'zh': 'zh',
    'ja': 'ja',
    'ar': 'ar',
    'hi': 'hi',
}

# DB Columns mapping
DB_COLUMNS = {
    'en': ('paintingname', 'description', 'style'),
    'ro': ('paintingname_ro', 'description_ro', 'style_ro'),
    'es': ('paintingname_es', 'description_es', 'style_es'),
    'de': ('paintingname_de', 'description_de', 'style_de'),
    'fr': ('paintingname_fr', 'description_fr', 'style_fr'),
    'it': ('paintingname_it', 'description_it', 'style_it'),
    'ru': ('paintingname_ru', 'description_ru', 'style_ru'),
    'pt': ('paintingname_pt', 'description_pt', 'style_pt'),
    'zh': ('paintingname_zh', 'description_zh', 'style_zh'),
    'ja': ('paintingname_ja', 'description_ja', 'style_ja'),
    'ar': ('paintingname_ar', 'description_ar', 'style_ar'),
    'hi': ('paintingname_hi', 'description_hi', 'style_hi'),
}

# Rate limiting (seconds)
RATE_LIMITS = {
    'powo': 0.5,
    'wikipedia': 0.3,
    'gbif': 0.2,
    'wikimedia': 1.0,
}

# Medicinal plant categories
MEDICINAL_CATEGORIES = {
    'adaptogen': {
        'name': 'Adaptogen',
        'name_ro': 'Adaptogen',
        'name_es': 'Adaptógeno',
        'name_de': 'Adaptogen',
        'name_fr': 'Adaptogène',
        'name_it': 'Adattogeno',
        'name_ru': 'Адаптоген',
        'name_pt': 'Adaptógeno',
        'name_zh': '适应原',
        'name_ja': '適応原',
        'name_ar': 'مكيف',
        'name_hi': 'अनुकूलक',
        'description': 'Herbs that help the body adapt to stress and restore balance',
        'keywords': ['adaptogen', 'stress-relieving', 'stress relief', 'anxiety', 'nervousness'],
    },
    'anti_inflammatory': {
        'name': 'Anti-inflammatory',
        'name_ro': 'Antiinflamator',
        'name_es': 'Antiinflamatorio',
        'name_de': 'Entzündungshemmend',
        'name_fr': 'Anti-inflammatoire',
        'name_it': 'Antinfiammatorio',
        'name_ru': 'Противовоспалительный',
        'name_pt': 'Anti-inflamatório',
        'name_zh': '抗炎',
        'name_ja': '抗炎症',
        'name_ar': 'مضاد للالتهاب',
        'name_hi': 'सूजन विरोधी',
        'description': 'Plants that reduce inflammation and swelling',
        'keywords': ['anti-inflammatory', 'inflammation', 'antiinflammatory', 'swelling'],
    },
    'antifungal': {
        'name': 'Antifungal',
        'name_ro': 'Antifungic',
        'name_es': 'Antifúngico',
        'name_de': 'Antimykotisch',
        'name_fr': 'Antifongique',
        'name_it': 'Antifungino',
        'name_ru': 'Противогрибковый',
        'name_pt': 'Antifúngico',
        'name_zh': '抗真菌',
        'name_ja': '抗真菌',
        'name_ar': 'مضاد للفطريات',
        'name_hi': 'एंटीफंगल',
        'description': 'Natural fungi fighters used in traditional medicine',
        'keywords': ['antifungal', 'fungus', 'fungal', 'antimycotic'],
    },
    'antiviral': {
        'name': 'Antiviral',
        'name_ro': 'Antiviral',
        'name_es': 'Antiviral',
        'name_de': 'Antiviral',
        'name_fr': 'Antiviral',
        'name_it': 'Antivirale',
        'name_ru': 'Противовирусный',
        'name_pt': 'Antiviral',
        'name_zh': '抗病毒',
        'name_ja': '抗ウイルス',
        'name_ar': 'مضاد للفيروسات',
        'name_hi': 'एंटीवायरल',
        'description': 'Plants with documented antiviral properties',
        'keywords': ['antiviral', 'viral', 'virus', 'antivirus'],
    },
    'antibacterial': {
        'name': 'Antibacterial',
        'name_ro': 'Antibacterian',
        'name_es': 'Antibacteriano',
        'name_de': 'Antibakteriell',
        'name_fr': 'Antibactérien',
        'name_it': 'Antibatterico',
        'name_ru': 'Антибактериальный',
        'name_pt': 'Antibacteriano',
        'name_zh': '抗菌',
        'name_ja': '抗菌',
        'name_ar': 'مضاد للبكتيريا',
        'name_hi': 'जीवाणुरोधी',
        'description': 'Natural antimicrobial and antibacterial herbs',
        'keywords': ['antibacterial', 'antiseptic', 'antimicrobial', 'bacterial', 'infection'],
    },
    'digestive': {
        'name': 'Digestive',
        'name_ro': 'Digestiv',
        'name_es': 'Digestivo',
        'name_de': 'Verdauung',
        'name_fr': 'Digestif',
        'name_it': 'Digestivo',
        'name_ru': 'Пищеварительный',
        'name_pt': 'Digestivo',
        'name_zh': '消化',
        'name_ja': '消化',
        'name_ar': 'هضم',
        'name_hi': 'पाचन',
        'description': 'Herbs that support digestion, reduce bloating and nausea',
        'keywords': ['digestive', 'digestion', 'stomach', 'bloating', 'nausea', 'indigestion'],
    },
    'nervine': {
        'name': 'Nervine',
        'name_ro': 'Nervos',
        'name_es': 'Nervino',
        'name_de': 'Nervenberuhigend',
        'name_fr': 'Nervine',
        'name_it': 'Nervino',
        'name_ru': 'Нервное',
        'name_pt': 'Nervino',
        'name_zh': '神经',
        'name_ja': '神経',
        'name_ar': 'أعصاب',
        'name_hi': 'नर्वस',
        'description': 'Calming herbs that support the nervous system',
        'keywords': ['nervine', 'calming', 'calm', 'sleep', 'relaxation', 'insomnia'],
    },
    'respiratory': {
        'name': 'Respiratory',
        'name_ro': 'Respirator',
        'name_es': 'Respiratorio',
        'name_de': 'Atemwegs',
        'name_fr': 'Respiratoire',
        'name_it': 'Respiratorio',
        'name_ru': 'Дыхательный',
        'name_pt': 'Respiratório',
        'name_zh': '呼吸',
        'name_ja': '呼吸',
        'name_ar': 'تنفسي',
        'name_hi': 'श्वसन',
        'description': 'Plants for coughs, colds, and lung health',
        'keywords': ['respiratory', 'cough', 'cold', 'lung', 'bronch', 'asthma'],
    },
    'cardiovascular': {
        'name': 'Cardiovascular',
        'name_ro': 'Cardiovascular',
        'name_es': 'Cardiovascular',
        'name_de': 'Kardiovaskulär',
        'name_fr': 'Cardiovasculaire',
        'name_it': 'Cardiovascolare',
        'name_ru': 'Сердечно-сосудистый',
        'name_pt': 'Cardiovascular',
        'name_zh': '心血管',
        'name_ja': '心血管',
        'name_ar': 'القلب والأوعية',
        'name_hi': 'हृदय संबंधी',
        'description': 'Herbs supporting heart health and circulation',
        'keywords': ['cardiovascular', 'heart', 'circulation', 'blood pressure', 'cardiac'],
    },
    'immunostimulant': {
        'name': 'Immunostimulant',
        'name_ro': 'Imunostimulant',
        'name_es': 'Inmunoestimulante',
        'name_de': 'Immunstimulans',
        'name_fr': 'Immunostimulant',
        'name_it': 'Immunostimolante',
        'name_ru': 'Иммуностимулятор',
        'name_pt': 'Imunoestimulante',
        'name_zh': '免疫刺激',
        'name_ja': '免疫刺激',
        'name_ar': 'محفز المناعة',
        'name_hi': 'प्रतिरक्षा उत्तेजक',
        'description': 'Plants that stimulate and strengthen the immune system',
        'keywords': ['immunostimulant', 'immune', 'immunity', 'infection', 'antimicrobial'],
    },
    'analgesic': {
        'name': 'Analgesic',
        'name_ro': 'Analgezic',
        'name_es': 'Analgésico',
        'name_de': 'Schmerzmittel',
        'name_fr': 'Analgésique',
        'name_it': 'Analgesico',
        'name_ru': 'Анальгетик',
        'name_pt': 'Analgésico',
        'name_zh': '止痛',
        'name_ja': '鎮痛',
        'name_ar': 'مسكن',
        'name_hi': 'दर्द निवारक',
        'description': 'Natural pain-relieving plants',
        'keywords': ['analgesic', 'pain relief', 'pain', 'anti-pain'],
    },
    'detoxifying': {
        'name': 'Detoxifying',
        'name_ro': 'Detoxifiant',
        'name_es': 'Desintoxicante',
        'name_de': 'Entgiftung',
        'name_fr': 'Détoxifiant',
        'name_it': 'Disintossicante',
        'name_ru': 'Детоксифицирующий',
        'name_pt': 'Desintoxicante',
        'name_zh': '排毒',
        'name_ja': 'デトックス',
        'name_ar': 'تطهير',
        'name_hi': 'विषहरण',
        'description': 'Liver, kidney, and lymph-supporting herbs',
        'keywords': ['detoxifying', 'detox', 'liver', 'kidney', 'lymph', 'cleansing'],
    },
    'tonic': {
        'name': 'Tonic',
        'name_ro': 'Tonic',
        'name_es': 'Tónico',
        'name_de': 'Tonikum',
        'name_fr': 'Tonique',
        'name_it': 'Tonico',
        'name_ru': 'Тоник',
        'name_pt': 'Tônico',
        'name_zh': '滋补',
        'name_ja': 'トニック',
        'name_ar': 'منشط',
        'name_hi': 'टॉनिक',
        'description': 'General vitality and strengthening herbs',
        'keywords': ['tonic', 'vitality', 'strengthening', 'general health'],
    },
}

# Quality thresholds
MIN_WIKIPEDIA_ARTICLE_LENGTH = 200  # chars
MIN_IMAGE_WIDTH = 50  # pixels
