#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Fix 22: Replace genus-taxonomy stubs with proper medicinal descriptions in ES/FR/IT/PT."""
import sqlite3, sys, io
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8', errors='replace')

DB = r'C:\Users\rsavu\AndroidStudioProjects\HerbalRedo\androidApp\src\main\assets\plants.db'

# Format: (id, lang, text) — only languages that had genus stubs
FIXES = [
# ── Dandelion [25] — es fr it genus stubs
(25,'es','El diente de león (Taraxacum officinale) es una planta medicinal perenne de la familia Asteraceae, ampliamente distribuida en regiones templadas del hemisferio norte. Sus raíces y hojas contienen taraxacina, flavonoides, inulina y vitaminas que estimulan la función hepática, biliar y digestiva. Utilizado durante siglos en la medicina tradicional europea y china para afecciones del hígado, dispepsia, retención de líquidos y artritis. La investigación moderna confirma sus propiedades diuréticas, antiinflamatorias, antioxidantes y prebióticas. Las hojas jóvenes se consumen también como verdura nutritiva rica en vitaminas A, C y K.'),
(25,'fr','Le pissenlit (Taraxacum officinale) est une plante médicinale vivace de la famille des Asteraceae, présente dans les régions tempérées du monde entier. Ses racines et feuilles renferment de la taraxacine, des flavonoïdes, de l'inuline et des vitamines qui stimulent les fonctions hépatique, biliaire et digestive. Utilisé depuis des siècles en phytothérapie européenne et chinoise pour les affections du foie, la dyspepsie, la rétention d'eau et les douleurs articulaires. Des études modernes confirment ses propriétés diurétiques, anti-inflammatoires, antioxydantes et prébiotiques. Les jeunes feuilles sont également consommées comme légume riche en vitamines A, C et K.'),
(25,'it','Il tarassaco (Taraxacum officinale) è una pianta medicinale perenne della famiglia delle Asteraceae, diffusa nelle regioni temperate dell\'emisfero nord. Le sue radici e foglie contengono taraxacina, flavonoidi, inulina e vitamine che stimolano le funzioni epatica, biliare e digestiva. Impiegato da secoli nella medicina tradizionale europea e cinese per affezioni epatiche, dispepsia, ritenzione idrica e dolori articolari. Ricerche moderne ne confermano le proprietà diuretiche, antinfiammatorie, antiossidanti e prebiotiche. Le giovani foglie vengono consumate come verdura nutriente ricca di vitamine A, C e K.'),
# ── Passiflora [92] — es fr it pt
(92,'es','La pasiflora (Passiflora incarnata) es una planta trepadora de la familia Passifloraceae, originaria del sureste de América del Norte. Sus hojas, tallos y flores contienen flavonoides (crisina, vitexina), alcaloides harmánicos e isovitexina, que ejercen efectos ansiolíticos, sedantes y espasmolíticos. Utilizada por los nativos americanos y la medicina europea para tratar la ansiedad, el insomnio, la histeria y los espasmos musculares. La Comisión E alemana ha aprobado su uso como sedante suave para el nerviosismo y los trastornos del sueño leves. También se investiga su actividad anticonvulsivante y como adyuvante en la reducción de síntomas de abstinencia.'),
(92,'fr','La passiflore (Passiflora incarnata) est une plante grimpante de la famille des Passifloraceae, originaire du sud-est de l\'Amérique du Nord. Ses feuilles, tiges et fleurs contiennent des flavonoïdes (chrysine, vitexine), des alcaloïdes harmaniques et de l\'isovitexine, qui exercent des effets anxiolytiques, sédatifs et spasmolytiques. Utilisée par les Amérindiens et la médecine européenne pour traiter l\'anxiété, l\'insomnie, l\'hystérie et les spasmes musculaires. La Commission E allemande a approuvé son usage comme sédatif doux pour la nervosité et les troubles légers du sommeil. Ses propriétés anticonvulsivantes et son rôle dans la réduction des symptômes de sevrage sont aussi étudiés.'),
(92,'it','La passiflora (Passiflora incarnata) è una pianta rampicante della famiglia delle Passifloraceae, originaria del sudest del Nord America. Le sue foglie, steli e fiori contengono flavonoidi (crisina, vitexina), alcaloidi harmanici e isovitexina, con effetti ansiolitici, sedativi e spasmolitici. Impiegata dai nativi americani e dalla medicina europea per ansia, insonnia, isteria e spasmi muscolari. La Commissione E tedesca ne ha approvato l\'uso come sedativo blando per nervosismo e disturbi lievi del sonno. Sono in studio anche le sue proprietà anticonvulsivanti e il ruolo nel ridurre i sintomi da astinenza.'),
(92,'pt','A passiflora (Passiflora incarnata) é uma planta trepadeira da família Passifloraceae, originária do sudeste da América do Norte. Suas folhas, caules e flores contêm flavonoides (crisina, vitexina), alcaloides harmânicos e isovitexina, com efeitos ansiolíticos, sedativos e espasmolíticos. Utilizada pelos povos indígenas americanos e pela medicina europeia para tratar ansiedade, insônia, histeria e espasmos musculares. A Comissão E alemã aprovou seu uso como sedativo suave para nervosismo e distúrbios leves do sono. Investiga-se também sua atividade anticonvulsivante e papel na redução de sintomas de abstinência.'),
# ── Angelica [143] — es fr it pt
(143,'es','La angélica (Angelica archangelica) es una hierba bienal aromática de la familia Apiaceae, nativa de las regiones templadas y subárticas del hemisferio norte. Sus raíces, semillas y tallos contienen cumarinas (angelicina, ostol), aceites esenciales, furanocumarinas y taninos que ejercen efectos antiespasmódicos, carminativos y expectorantes. Empleada desde la Edad Media en Europa para tratar la dispepsia, la flatulencia, la bronquitis crónica y los espasmos gástricos. La decocción de la raíz estimula la producción de jugos digestivos y bilis, siendo ingrediente tradicional de licores digestivos como el Chartreuse y el Bénédictine. La investigación moderna documenta también propiedades antimicrobianas y antiinflamatorias.'),
(143,'fr','L\'angélique (Angelica archangelica) est une herbe bisannuelle aromatique de la famille des Apiaceae, native des régions tempérées et subarctiques de l\'hémisphère nord. Ses racines, graines et tiges contiennent des coumarines (angélicine, osthol), des huiles essentielles, des furanocoumarines et des tanins aux effets antispasmodiques, carminatifs et expectorants. Utilisée depuis le Moyen Âge en Europe pour traiter la dyspepsie, les flatulences, la bronchite chronique et les spasmes gastriques. La décoction de racine stimule la production de sucs digestifs et de bile, et figure comme ingrédient traditionnel des liqueurs digestives telles que la Chartreuse et la Bénédictine. Des recherches modernes documentent en outre ses propriétés antimicrobiennes et anti-inflammatoires.'),
(143,'it','L\'angelica (Angelica archangelica) è un\'erba biennale aromatica della famiglia delle Apiaceae, originaria delle regioni temperate e subartiche dell\'emisfero nord. Le sue radici, semi e fusti contengono cumarine (angelicina, ostolo), oli essenziali, furanocumarine e tannini con effetti antispasmodici, carminativi ed espettoranti. Impiegata fin dal Medioevo in Europa per dispepsia, flatulenza, bronchite cronica e spasmi gastrici. Il decotto di radice stimola la produzione di succhi digestivi e bile, ed è ingrediente tradizionale di liquori digestivi come la Chartreuse e il Bénédictine. Ricerche moderne documentano anche proprietà antimicrobiche e antinfiammatorie.'),
(143,'pt','A angélica (Angelica archangelica) é uma erva bienal aromática da família Apiaceae, nativa das regiões temperadas e subárticas do hemisfério norte. Suas raízes, sementes e caules contêm cumarinas (angelicina, ostol), óleos essenciais, furanocumarinas e taninos com efeitos antiespasmódicos, carminativos e expectorantes. Utilizada desde a Idade Média na Europa para tratar dispepsia, flatulência, bronquite crónica e espasmos gástricos. A decocção da raiz estimula a produção de sucos digestivos e bílis, sendo ingrediente tradicional de licores digestivos como a Chartreuse e o Bénédictine. A pesquisa moderna documenta também propriedades antimicrobianas e anti-inflamatórias.'),
# ── Vervain [182] — es fr it pt
(182,'es','La verbena (Verbena officinalis) es una planta perenne de la familia Verbenaceae, nativa de Europa, norte de África y Asia occidental. Contiene iridoides (verbascósido, aucubósido), flavonoides, taninos y alcaloides que le confieren propiedades antiinflamatorias, hepatoprotectoras, nervinas y febrífugas. En la medicina herbal europea tradicional se utiliza para tratar ansiedad, insomnio, dolores de cabeza, afecciones hepáticas y fiebres. El "Juicio de Salomón" la consagraba como planta sagrada, y fue empleada en rituales romanos y druídicos. La investigación moderna investiga su actividad analgésica, antimicrobiana y neuroprotectora.'),
(182,'fr','La verveine (Verbena officinalis) est une plante vivace de la famille des Verbenaceae, native d\'Europe, d\'Afrique du Nord et d\'Asie occidentale. Elle contient des iridoïdes (verbascosides, aucubosides), des flavonoïdes, des tanins et des alcaloïdes aux propriétés anti-inflammatoires, hépatoprotectrices, nerveuses et fébrifuges. Utilisée en phytothérapie européenne traditionnelle pour traiter l\'anxiété, l\'insomnie, les céphalées, les affections hépatiques et les fièvres. Considérée comme plante sacrée par les Romains et les Druides. Des recherches modernes étudient son activité analgésique, antimicrobienne et neuroprotectrice.'),
(182,'it','La verbena (Verbena officinalis) è una pianta perenne della famiglia delle Verbenaceae, originaria di Europa, Nord Africa e Asia occidentale. Contiene iridoidi (verbascosidi, aucubosidi), flavonoidi, tannini e alcaloidi con proprietà antinfiammatorie, epatoprotettive, nervine e febbrifughe. Nella fitoterapia erboristica europea viene usata per ansia, insonnia, cefalee, affezioni epatiche e stati febbrili. Considerata pianta sacra da Romani e Druidi. Ricerche moderne ne studiano l\'attività analgesica, antimicrobica e neuroprotettrice.'),
(182,'pt','A verbena (Verbena officinalis) é uma planta perene da família Verbenaceae, nativa da Europa, Norte de África e Ásia Ocidental. Contém iridoides (verbascosídeo, aucubosídeo), flavonoides, taninos e alcaloides com propriedades anti-inflamatórias, hepatoprotetoras, nervinas e febrifugas. Na fitoterapia europeia tradicional é utilizada para ansiedade, insônia, cefaleias, afecções hepáticas e febres. Considerada planta sagrada por romanos e druidas. A investigação moderna estuda a sua atividade analgésica, antimicrobiana e neuroprotetora.'),
# ── Hibiscus [229] — es fr it pt
(229,'es','El hibisco (Hibiscus sabdariffa y H. rosa-sinensis) es un género de plantas de la familia Malvaceae ampliamente valorado por sus propiedades medicinales. Los cálices del hibisco de Jamaica contienen antocianos (delfinidina, cianidina), ácidos orgánicos, flavonoides y mucílagos que ejercen efectos antihipertensivos, antioxidantes, diuréticos y hepatoprotectores. Los estudios clínicos han demostrado que el té de hibisco reduce significativamente la presión arterial y los niveles de colesterol LDL en pacientes con hipertensión leve. Las flores se emplean también en la medicina ayurvédica y africana para tratar fiebres, problemas digestivos e inflamaciones. El extracto de H. sabdariffa está siendo investigado por sus propiedades antidiabéticas y antibacterianas.'),
(229,'fr','L\'hibiscus (Hibiscus sabdariffa et H. rosa-sinensis) est un genre de plantes de la famille des Malvacées largement reconnu pour ses propriétés médicinales. Les calices de l\'hibiscus de Jamaïque contiennent des anthocyanes (delphidine, cyanidine), des acides organiques, des flavonoïdes et des mucilages aux effets antihypertenseurs, antioxydants, diurétiques et hépatoprotecteurs. Des études cliniques ont démontré que le thé d\'hibiscus réduit significativement la pression artérielle et le cholestérol LDL chez les patients souffrant d\'hypertension légère. Les fleurs sont également utilisées en médecine ayurvédique et africaine pour soigner les fièvres, troubles digestifs et inflammations. L\'extrait de H. sabdariffa est étudié pour ses propriétés antidiabétiques et antibactériennes.'),
(229,'it','L\'ibisco (Hibiscus sabdariffa e H. rosa-sinensis) è un genere di piante della famiglia delle Malvacee molto apprezzato per le sue proprietà medicinali. I calici dell\'ibisco giamaicano contengono antociani (delfinidina, cianidina), acidi organici, flavonoidi e mucillagini con effetti antipertensivi, antiossidanti, diuretici ed epatoprotettivi. Studi clinici hanno dimostrato che il tè di ibisco riduce significativamente la pressione arteriosa e il colesterolo LDL nei pazienti con ipertensione lieve. I fiori sono impiegati anche nella medicina ayurvedica e africana per febbre, disturbi digestivi e infiammazioni. L\'estratto di H. sabdariffa è studiato per le proprietà antidiabetiche e antibatteriche.'),
(229,'pt','O hibisco (Hibiscus sabdariffa e H. rosa-sinensis) é um género de plantas da família Malvaceae amplamente valorizado pelas suas propriedades medicinais. Os cálices do hibisco da Jamaica contêm antocianinas (delfidina, cianidina), ácidos orgânicos, flavonoides e mucilagens com efeitos anti-hipertensivos, antioxidantes, diuréticos e hepatoprotetores. Estudos clínicos demonstraram que o chá de hibisco reduz significativamente a pressão arterial e o colesterol LDL em doentes com hipertensão ligeira. As flores são também utilizadas na medicina ayurvédica e africana para febre, problemas digestivos e inflamações. O extrato de H. sabdariffa está a ser investigado pelas suas propriedades antidiabéticas e antibacterianas.'),
# ── Ephedra [240] — es fr it pt
(240,'es','La efedra (Ephedra sinica y E. intermedia) es un arbusto gimnospermo de la familia Ephedraceae, nativo de las zonas áridas de Asia. Sus tallos contienen efedrina, pseudoefedrina, norefedrina y taninos que tienen efectos broncodilatadores, vasoconstrictores y estimulantes del sistema nervioso central. Empleada en la medicina china tradicional (ma huang) durante más de 5.000 años para tratar el asma, la bronquitis, las congestiones nasales y el resfriado. La efedrina es un componente activo de numerosos medicamentos antiasmáticos y descongestionantes modernos. Debido a su potencial de abuso y efectos cardiovasculares adversos, su uso está estrictamente regulado en muchos países.'),
(240,'fr','L\'éphédra (Ephedra sinica et E. intermedia) est un arbuste gymnosperme de la famille des Éphédraceae, natif des zones arides d\'Asie. Ses tiges contiennent de l\'éphédrine, de la pseudoéphédrine, de la noréphédrine et des tanins aux effets bronchodilatateurs, vasoconstricteurs et stimulants du système nerveux central. Utilisé en médecine traditionnelle chinoise (ma huang) depuis plus de 5 000 ans pour traiter l\'asthme, la bronchite, les congestions nasales et le rhume. L\'éphédrine est un composant actif de nombreux médicaments antiasthmatiques et décongestionnants modernes. En raison de son potentiel d\'abus et d\'effets cardiovasculaires indésirables, son usage est strictement réglementé dans de nombreux pays.'),
(240,'it','L\'efedra (Ephedra sinica ed E. intermedia) è un arbusto gimnosperma della famiglia delle Ephedraceae, nativo delle zone aride dell\'Asia. I suoi steli contengono efedrina, pseudoefedrina, norefedrina e tannini con effetti broncodilatatori, vasocostritivi e stimolanti del sistema nervoso centrale. Impiegata nella medicina tradizionale cinese (ma huang) da oltre 5.000 anni per asma, bronchite, congestioni nasali e raffreddore. L\'efedrina è un principio attivo di molti farmaci antiastmatici e decongestionanti moderni. A causa del suo potenziale di abuso e degli effetti cardiovascolari avversi, l\'uso è strettamente regolamentato in molti paesi.'),
(240,'pt','A efedra (Ephedra sinica e E. intermedia) é um arbusto gimnospérmico da família Ephedraceae, nativo das zonas áridas da Ásia. Os seus caules contêm efedrina, pseudoefedrina, norefedrina e taninos com efeitos broncodilatadores, vasoconstritores e estimulantes do sistema nervoso central. Utilizada na medicina tradicional chinesa (ma huang) há mais de 5.000 anos para tratar asma, bronquite, congestão nasal e resfriado. A efedrina é um componente ativo de muitos medicamentos antiasmáticos e descongestionantes modernos. Devido ao seu potencial de abuso e efeitos cardiovasculares adversos, o seu uso está estritamente regulamentado em muitos países.'),
# ── Buckthorn [261] — es fr it pt
(261,'es','El espino cerval (Rhamnus cathartica y Frangula alnus) es un arbusto de la familia Rhamnaceae, nativo de Europa y Asia occidental. Su corteza contiene antraquinonas (emodina, ramnosida, frangulina), glucósidos y taninos que ejercen un potente efecto laxante estimulante sobre el intestino grueso. Utilizado durante siglos en la medicina herbal europea para el estreñimiento crónico, la hidropesía y las infecciones intestinales. El frangulósido (Frangula alnus) es el componente de preparaciones laxantes de acción suave aprobadas por la Comisión E alemana. Se debe usar durante períodos limitados dado el potencial de hipocalemia y melanosis coli con uso prolongado.'),
(261,'fr','Le nerprun (Rhamnus cathartica et Frangula alnus) est un arbuste de la famille des Rhamnacées, natif d\'Europe et d\'Asie occidentale. Son écorce contient des anthraquinones (émodine, ramnoside, franguline), des glucosides et des tanins aux puissants effets laxatifs stimulants sur le gros intestin. Utilisé pendant des siècles en phytothérapie européenne pour la constipation chronique, l\'hydropisie et les infections intestinales. La franguline (Frangula alnus) est le composant de préparations laxatives douces approuvées par la Commission E allemande. L\'usage doit être limité dans le temps en raison du risque d\'hypokaliémie et de mélanose colique à long terme.'),
(261,'it','Il ranno purgativo (Rhamnus cathartica e Frangula alnus) è un arbusto della famiglia delle Ramnacee, nativo di Europa e Asia occidentale. La sua corteccia contiene antrachinoni (emodina, ramnoside, franguline), glucosidi e tannini con potenti effetti lassativi stimolanti sul colon. Impiegato per secoli nella fitoterapia europea per stipsi cronica, idropisie e infezioni intestinali. Il franguloside (Frangula alnus) è il componente di preparazioni lassative blande approvate dalla Commissione E tedesca. L\'uso deve essere limitato nel tempo a causa del rischio di ipokaliemia e melanosi colica con uso prolungato.'),
(261,'pt','O espinheiro cerval (Rhamnus cathartica e Frangula alnus) é um arbusto da família Rhamnaceae, nativo da Europa e Ásia Ocidental. A sua casca contém antraquinonas (emodina, ramnosídeo, frangulina), glucosídeos e taninos com potentes efeitos laxantes estimulantes sobre o intestino grosso. Utilizado durante séculos na fitoterapia europeia para obstipação crónica, hidropsia e infeções intestinais. O frangulósido (Frangula alnus) é o componente de preparações laxantes suaves aprovadas pela Comissão E alemã. O uso deve ser limitado no tempo devido ao risco de hipocalemia e melanose cólica com uso prolongado.'),
# ── Cinchona [20] — es it pt
(20,'es','La cinchona o quina (Cinchona officinalis y C. pubescens) es un árbol de la familia Rubiaceae, nativo de los bosques tropicales andinos de América del Sur. Su corteza contiene quinina, quinidina, cinconina y cinconidina (alcaloides quinolínicos) que poseen propiedades antipalúdicas, antipiréticas, antiarrítmicas y amargas digestivas. Fue la fuente original de quinina, el primer tratamiento efectivo contra la malaria, descubierto por los pueblos indígenas del Perú y Ecuador, y llevado a Europa en el siglo XVII. La quinidina se utiliza aún hoy en la medicina moderna como antiarrítmico cardíaco. La corteza de quina es también ingrediente del vermut y de bebidas amargas digestivas.'),
(20,'it','Il chinchona o china (Cinchona officinalis e C. pubescens) è un albero della famiglia delle Rubiaceae, nativo delle foreste tropicali andine del Sud America. La sua corteccia contiene chinina, chinidina, cinconina e cinconidina (alcaloidi chinolinici) con proprietà antimalariche, antipiretiche, antiaritmiche e amaricanti digestive. Fu la fonte originale della chinina, primo trattamento efficace contro la malaria, scoperto dai popoli indigeni di Perù ed Ecuador e portato in Europa nel XVII secolo. La chinidina è ancora usata oggi come antiaritmico cardiaco. La corteccia di china è anche ingrediente del vermut e di bevande amare digestive.'),
(20,'pt','A cinchona ou quina (Cinchona officinalis e C. pubescens) é uma árvore da família Rubiaceae, nativa das florestas tropicais andinas da América do Sul. A sua casca contém quinina, quinidina, cinconina e cinconidina (alcaloides quinolínicos) com propriedades antimaláricas, antipiréticas, antiarrítmicas e amaricantes digestivas. Foi a fonte original da quinina, primeiro tratamento eficaz contra a malária, descoberto pelos povos indígenas do Peru e Equador e trazido para a Europa no século XVII. A quinidina é ainda hoje utilizada como antiarrítmico cardíaco. A casca de quina é também ingrediente do vermute e de bebidas amargas digestivas.'),
# ── Echinacea / Narrow-leaved Coneflower [344] — es fr it pt
(344,'es','La equinácea de hoja estrecha (Echinacea angustifolia) es una planta perenne de la familia Asteraceae, nativa de las praderas del centro de América del Norte. Su raíz contiene alquilamidas, polisacáridos (equinacina), glucoproteínas y ácido chicórico que estimulan la respuesta inmune innata y adaptativa. Empleada durante siglos por los pueblos nativos americanos como remedio para infecciones, heridas y picaduras de serpiente, y adoptada posteriormente por la medicina herbal europea y norteamericana. Los meta-análisis clínicos indican una reducción moderada de la duración y la gravedad del resfriado común. La Comisión E aprueba su uso para el apoyo inmune en infecciones respiratorias y urinarias agudas.'),
(344,'fr','L\'échinacée à feuilles étroites (Echinacea angustifolia) est une plante vivace de la famille des Asteraceae, native des prairies du centre de l\'Amérique du Nord. Sa racine contient des alkylamides, des polysaccharides (échinacine), des glycoprotéines et de l\'acide cichorique qui stimulent la réponse immunitaire innée et adaptative. Utilisée pendant des siècles par les peuples autochtones d\'Amérique du Nord comme remède contre les infections, les blessures et les morsures de serpent, puis adoptée par la phytothérapie européenne et nord-américaine. Des méta-analyses cliniques indiquent une réduction modérée de la durée et de la gravité du rhume commun. La Commission E approuve son utilisation pour le soutien immunitaire dans les infections respiratoires et urinaires aiguës.'),
(344,'it','L\'echinacea angustifolia (Echinacea angustifolia) è una pianta perenne della famiglia delle Asteraceae, nativa delle praterie del centro del Nord America. La sua radice contiene alchilammidi, polisaccaridi (echinacea), glicoproteine e acido cicorico che stimolano la risposta immunitaria innata e adattativa. Impiegata per secoli dai popoli nativi nordamericani come rimedio per infezioni, ferite e morsi di serpente, poi adottata dalla fitoterapia europea e nordamericana. Meta-analisi cliniche indicano una moderata riduzione della durata e gravità del raffreddore comune. La Commissione E approva il suo utilizzo per il supporto immunitario nelle infezioni respiratorie e urinarie acute.'),
(344,'pt','A equinácea de folha estreita (Echinacea angustifolia) é uma planta perene da família Asteraceae, nativa das pradarias do centro da América do Norte. A sua raiz contém alquilamidas, polissacarídeos (equinacina), glicoproteínas e ácido cicórico que estimulam a resposta imunitária inata e adaptativa. Utilizada durante séculos pelos povos nativos norte-americanos como remédio para infeções, feridas e picadas de cobra, sendo depois adotada pela fitoterapia europeia e norte-americana. Meta-análises clínicas indicam uma redução moderada da duração e gravidade do resfriado comum. A Comissão E aprova o seu uso para suporte imunitário em infeções respiratórias e urinárias agudas.'),
# ── Barberry [369] — es fr it pt
(369,'es','El agracejo (Berberis vulgaris) es un arbusto espinoso de la familia Berberidaceae, ampliamente distribuido en regiones templadas del mundo. Sus corteza, raíz y frutos contienen berberina, berbamina, oxiacantina y taninos con potentes propiedades antibacterianas, antiinflamatorias, hipoglucemiantes y colagogas. Utilizado en la medicina herbal persa, ayurvédica, china y europea para afecciones hepáticas y biliares, infecciones digestivas, hipertensión y diabetes. La berberina ha sido extensamente estudiada en ensayos clínicos y muestra eficacia en la reducción de glucosa y colesterol comparables a algunos fármacos convencionales. Las bayas ácidas son ricas en vitamina C y se utilizan en la gastronomía del Oriente Medio.'),
(369,'fr','L\'épine-vinette (Berberis vulgaris) est un arbuste épineux de la famille des Berbéridacées, largement répandu dans les régions tempérées du monde. Son écorce, sa racine et ses fruits contiennent de la berbérine, de la berbamine, de l\'oxiacanthine et des tanins aux puissantes propriétés antibactériennes, anti-inflammatoires, hypoglycémiantes et cholagogues. Utilisé en médecine persane, ayurvédique, chinoise et européenne pour les affections hépatiques et biliaires, les infections digestives, l\'hypertension et le diabète. La berbérine a été largement étudiée dans des essais cliniques et montre une efficacité de réduction du glucose et du cholestérol comparable à certains médicaments conventionnels. Les baies acidulées sont riches en vitamine C et utilisées dans la gastronomie du Proche-Orient.'),
(369,'it','Il crespino (Berberis vulgaris) è un arbusto spinoso della famiglia delle Berberidacee, ampiamente distribuito nelle regioni temperate del mondo. La sua corteccia, radice e frutti contengono berberina, berbamina, oxiacantina e tannini con potenti proprietà antibatteriche, antinfiammatorie, ipoglicemizzanti e colagoghe. Impiegato nella medicina erboristica persiana, ayurvedica, cinese ed europea per affezioni epatiche e biliari, infezioni digestive, ipertensione e diabete. La berberina è stata ampiamente studiata in trial clinici e mostra efficacia nella riduzione di glucosio e colesterolo paragonabile ad alcuni farmaci convenzionali. Le bacche acide sono ricche di vitamina C e utilizzate nella gastronomia mediorientale.'),
(369,'pt','O espinho-do-diabo (Berberis vulgaris) é um arbusto espinhoso da família Berberidaceae, amplamente distribuído nas regiões temperadas do mundo. A sua casca, raiz e frutos contêm berberina, berbamina, oxiacantina e taninos com potentes propriedades antibacterianas, anti-inflamatórias, hipoglicemiantes e colagogas. Utilizado na medicina herbal persa, ayurvédica, chinesa e europeia para afecções hepáticas e biliares, infeções digestivas, hipertensão e diabetes. A berberina tem sido amplamente estudada em ensaios clínicos e mostra eficácia na redução de glucose e colesterol comparável a alguns fármacos convencionais. As bagas ácidas são ricas em vitamina C e utilizadas na gastronomia do Médio Oriente.'),
# ── Sumac [304] — es fr it pt
(304,'es','El zumaque (Rhus coriaria) es un arbusto de la familia Anacardiaceae, nativo de la cuenca mediterránea y Oriente Medio. Sus frutos, hojas y corteza contienen ácido gálico, taninos hidrolizables, flavonoides y ácido málico que le confieren propiedades antioxidantes, astringentes, antiinflamatorias y antimicrobianas. En la medicina tradicional árabe y persa se ha utilizado para tratar diarrea, úlceras bucales, fiebre y problemas urinarios. El polvo del fruto es una especia fundamental en la cocina levantina, apreciada por su sabor ácido y sus propiedades conservantes. Estudios modernos documentan actividad hipoglucemiante, hipolipemiante y anticancerígena de los extractos de zumaque.'),
(304,'fr','Le sumac (Rhus coriaria) est un arbuste de la famille des Anacardiacées, natif du bassin méditerranéen et du Moyen-Orient. Ses fruits, feuilles et écorce contiennent de l\'acide gallique, des tanins hydrolysables, des flavonoïdes et de l\'acide malique aux propriétés antioxydantes, astringentes, anti-inflammatoires et antimicrobiennes. Dans la médecine traditionnelle arabe et persane, il est utilisé pour traiter la diarrhée, les ulcères buccaux, la fièvre et les problèmes urinaires. La poudre du fruit est une épice fondamentale de la cuisine levantine, appréciée pour sa saveur acide et ses propriétés conservantes. Des études modernes documentent une activité hypoglycémiante, hypolipémiante et anticancéreuse des extraits de sumac.'),
(304,'it','Il sommacco (Rhus coriaria) è un arbusto della famiglia delle Anacardiacee, nativo del bacino mediterraneo e del Medio Oriente. I suoi frutti, foglie e corteccia contengono acido gallico, tannini idrolizzabili, flavonoidi e acido malico con proprietà antiossidanti, astringenti, antinfiammatorie e antimicrobiche. Nella medicina tradizionale araba e persiana è impiegato per diarrea, ulcere orali, febbre e problemi urinari. La polvere del frutto è una spezia fondamentale della cucina levantina, apprezzata per il sapore acido e le proprietà conservanti. Studi moderni documentano attività ipoglicemizzante, ipolipemizzante e anticancerosa degli estratti di sommacco.'),
(304,'pt','O sumagre (Rhus coriaria) é um arbusto da família Anacardiaceae, nativo da bacia mediterrânica e do Médio Oriente. Os seus frutos, folhas e casca contêm ácido gálico, taninos hidrolisáveis, flavonoides e ácido málico com propriedades antioxidantes, adstringentes, anti-inflamatórias e antimicrobianas. Na medicina tradicional árabe e persa é utilizado para tratar diarreia, úlceras orais, febre e problemas urinários. O pó do fruto é uma especiaria fundamental na culinária levantina, apreciado pelo seu sabor ácido e propriedades conservantes. Estudos modernos documentam atividade hipoglicemiante, hipolipemiante e anticancerígena dos extratos de sumagre.'),
# ── Sweet Gum [300] — es fr it pt
(300,'es','El liquidámbar (Liquidambar styraciflua) es un árbol caducifolio de la familia Altingiaceae, nativo del sureste de América del Norte y México. Su resina (bálsamo de liquidámbar o estoraque americano) contiene estireno, ácido cinámico, resinas de bálsamo y aceite esencial con propiedades antisépticas, expectorantes, antiinflamatorias y cicatrizantes. Utilizado por los pueblos indígenas norteamericanos para tratar heridas, infecciones cutáneas y problemas respiratorios. La resina fue exportada a Europa en el siglo XVI donde se utilizó como incienso medicinal y en preparados para la piel. Las hojas y la corteza contienen ácido shikímico, precursor del antiviral oseltamivir (Tamiflu).'),
(300,'fr','Le liquidambar (Liquidambar styraciflua) est un arbre à feuilles caduques de la famille des Altingiaceae, natif du sud-est de l\'Amérique du Nord et du Mexique. Sa résine (baume de liquidambar ou storax américain) contient du styrène, de l\'acide cinnamique, des résines balsamiques et une huile essentielle aux propriétés antiseptiques, expectorantes, anti-inflammatoires et cicatrisantes. Utilisé par les peuples autochtones nord-américains pour traiter les plaies, les infections cutanées et les troubles respiratoires. La résine fut exportée vers l\'Europe au XVIe siècle et utilisée comme encens médicinal et dans des préparations pour la peau. Les feuilles et l\'écorce contiennent de l\'acide shikimique, précurseur de l\'antiviral oseltamivir (Tamiflu).'),
(300,'it','Il liquidambar (Liquidambar styraciflua) è un albero a foglie caduche della famiglia delle Altingiaceae, nativo del sudest del Nord America e del Messico. La sua resina (balsamo di liquidambar o storace americano) contiene stirene, acido cinnamico, resine balsamiche e olio essenziale con proprietà antisettiche, espettoranti, antinfiammatorie e cicatrizzanti. Impiegato dai popoli indigeni nordamericani per ferite, infezioni cutanee e problemi respiratori. La resina fu esportata in Europa nel XVI secolo, dove venne usata come incenso medicinale e in preparazioni per la pelle. Le foglie e la corteccia contengono acido shikimico, precursore dell\'antivirale oseltamivir (Tamiflu).'),
(300,'pt','O liquidâmbar (Liquidambar styraciflua) é uma árvore caducifólia da família Altingiaceae, nativa do sudeste da América do Norte e México. A sua resina (bálsamo de liquidâmbar ou estoraque americano) contém estireno, ácido cinâmico, resinas balsâmicas e óleo essencial com propriedades antissépticas, expectorantes, anti-inflamatórias e cicatrizantes. Utilizado pelos povos indígenas norte-americanos para feridas, infeções cutâneas e problemas respiratórios. A resina foi exportada para a Europa no século XVI, onde foi utilizada como incenso medicinal e em preparações para a pele. As folhas e a casca contêm ácido chiquímico, precursor do antiviral oseltamivir (Tamiflu).'),
# ── Luffa [653] — es fr it pt
(653,'es','La lufa (Luffa aegyptiaca y L. acutangula) es una planta trepadora tropical de la familia Cucurbitaceae, cultivada en Asia, África y América por sus frutos comestibles y esponjas vegetales. Sus frutos inmaduros son ricos en saponinas, cucurbitacinas, flavonoides y vitaminas con propiedades antiinflamatorias, analgésicas y laxantes. En la medicina ayurvédica y tradicional china se utilizan para tratar reumatismo, afecciones hepáticas, bronquitis y problemas menstruales. La esponja de lufa madura (fibra vascular lignificada) se emplea en cosmética y medicina para exfoliación cutánea y limpieza terapéutica. Los extractos de semilla presentan actividad antidiabética y antioxidante en modelos experimentales.'),
(653,'fr','La luffa (Luffa aegyptiaca et L. acutangula) est une plante grimpante tropicale de la famille des Cucurbitacées, cultivée en Asie, Afrique et Amérique pour ses fruits comestibles et ses éponges végétales. Ses fruits immatures sont riches en saponines, cucurbitacines, flavonoïdes et vitamines aux propriétés anti-inflammatoires, analgésiques et laxatives. Dans la médecine ayurvédique et traditionnelle chinoise, ils sont utilisés pour traiter les rhumatismes, les affections hépatiques, la bronchite et les troubles menstruels. L\'éponge de luffa mûre (fibre vasculaire lignifiée) est utilisée en cosmétique et en médecine pour l\'exfoliation cutanée et le nettoyage thérapeutique. Les extraits de graines présentent une activité antidiabétique et antioxydante dans des modèles expérimentaux.'),
(653,'it','La luffa (Luffa aegyptiaca e L. acutangula) è una pianta rampicante tropicale della famiglia delle Cucurbitacee, coltivata in Asia, Africa e America per i suoi frutti commestibili e le spugne vegetali. I suoi frutti immaturi sono ricchi di saponine, cucurbitacine, flavonoidi e vitamine con proprietà antinfiammatorie, analgesiche e lassative. Nella medicina ayurvedica e tradizionale cinese viene usata per reumatismi, affezioni epatiche, bronchite e disturbi mestruali. La spugna di luffa matura (fibra vascolare lignificata) è impiegata in cosmetica e medicina per l\'esfoliazione cutanea. Gli estratti di seme mostrano attività antidiabetica e antiossidante in modelli sperimentali.'),
(653,'pt','A luffa (Luffa aegyptiaca e L. acutangula) é uma planta trepadeira tropical da família Cucurbitaceae, cultivada na Ásia, África e América pelos seus frutos comestíveis e esponjas vegetais. Os seus frutos imaturos são ricos em saponinas, cucurbitacinas, flavonoides e vitaminas com propriedades anti-inflamatórias, analgésicas e laxativas. Na medicina ayurvédica e tradicional chinesa é utilizada para reumatismo, afecções hepáticas, bronquite e problemas menstruais. A esponja de luffa madura (fibra vascular lenhificada) é usada em cosmética e medicina para esfoliação cutânea. Os extratos de semente mostram atividade antidiabética e antioxidante em modelos experimentais.'),
# ── Quassia [275] — es it pt
(275,'es','El cuasia (Quassia amara y Picrasma excelsa) es un árbol o arbusto de la familia Simaroubaceae, nativo de América Central, el Caribe y el norte de América del Sur. Su madera y corteza contienen quasinoides (quasina, neoquasina) e iridoides con propiedades amargo-tónicas, aperitivas, antiparasitarias y antiprotozoarias. En la medicina herbal sudamericana se utiliza para tratar dispepsia, anorexia, fiebres palúdicas, gusanos intestinales y piojos. La quasina tiene actividad antimalárica in vitro y ha sido investigada como acaricida y nematicida natural. El extracto acuoso de madera se emplea como insecticida botánico de baja toxicidad para mamíferos.'),
(275,'it','Il quassia (Quassia amara e Picrasma excelsa) è un albero o arbusto della famiglia delle Simarubacee, nativo dell\'America Centrale, dei Caraibi e del nord del Sud America. Il suo legno e corteccia contengono quasinoidi (quassina, neoquassina) e iridoidi con proprietà amaro-toniche, aperitive, antiparassitarie e antiprotozoarie. Nella medicina erboristica sudamericana è usato per dispepsia, anoressia, febbre malarica, vermi intestinali e pidocchi. La quassina ha attività antimalarica in vitro ed è stata studiata come acaricida e nematicida naturale. L\'estratto acquoso del legno viene impiegato come insetticida botanico a bassa tossicità per i mammiferi.'),
(275,'pt','O quássia (Quassia amara e Picrasma excelsa) é uma árvore ou arbusto da família Simaroubaceae, nativo da América Central, Caraíbas e norte da América do Sul. A sua madeira e casca contêm quasinoides (quassina, neoquassina) e iridoides com propriedades amargo-tônicas, aperitivas, antiparasitárias e antiprotozoárias. Na medicina herbal sul-americana é utilizado para dispepsia, anorexia, febres malárias, vermes intestinais e piolhos. A quassina tem atividade antimalárica in vitro e foi investigada como acaricida e nematicida natural. O extrato aquoso da madeira é empregado como inseticida botânico de baixa toxicidade para mamíferos.'),
# ── Mullein [273] — es it pt
(273,'es','El gordolobo (Verbascum thapsus) es una planta bienal de la familia Scrophulariaceae, originaria de Europa, norte de África y Asia, ampliamente naturalizada. Sus flores, hojas y raíces contienen mucílagos, saponinas (verbascosapina), flavonoides (hesperidina, rutina) e iridoides con propiedades expectorantes, emolientes, antiinflamatorias y antivíricas. Empleado durante siglos en la medicina herbal europea para afecciones respiratorias: tos, bronquitis, asma, laringitis y catarros. Las flores maceradas en aceite de oliva son un remedio tradicional para el dolor de oído y la otitis. Investigaciones modernas han documentado actividad antivírica frente a herpes, influenza y virus respiratorios sincitiales.'),
(273,'it','Il verbasco (Verbascum thapsus) è una pianta biennale della famiglia delle Scrofulariacee, originaria di Europa, Nord Africa e Asia, ampiamente naturalizzata. I suoi fiori, foglie e radici contengono mucillagini, saponine (verbascosaponina), flavonoidi (esperidina, rutina) e iridoidi con proprietà espettoranti, emollienti, antinfiammatorie e antivirali. Impiegato per secoli nella fitoterapia europea per affezioni respiratorie: tosse, bronchite, asma, laringite e catarri. I fiori macerati in olio d\'oliva sono un rimedio tradizionale per il dolore all\'orecchio e l\'otite. Ricerche moderne hanno documentato attività antivirale contro herpes, influenza e virus respiratorio sinciziale.'),
(273,'pt','O verbasco (Verbascum thapsus) é uma planta bienal da família Scrophulariaceae, originária da Europa, Norte de África e Ásia, amplamente naturalizada. As suas flores, folhas e raízes contêm mucilagens, saponinas (verbascosaponina), flavonoides (hesperidina, rutina) e iridoides com propriedades expectorantes, emolientes, anti-inflamatórias e antivirais. Utilizado durante séculos na fitoterapia europeia para afecções respiratórias: tosse, bronquite, asma, laringite e catarros. As flores maceradas em azeite são um remédio tradicional para a dor de ouvido e otite. Investigações modernas documentaram atividade antiviral contra herpes, influenza e vírus respiratório sincicial.'),
# ── Nasturtium [285] — es it pt (Tropaeolum, not Watercress)
(285,'es','La capuchina o mastuerzo (Tropaeolum majus) es una planta trepadora o rastrera anual de la familia Tropaeolaceae, originaria de las regiones montañosas de América del Sur. Sus hojas, flores y semillas contienen glucosinolatos (glucotropaeolina), isotiocianatos (bencil-ITC), quercetina y vitamina C con propiedades antibacterianas, antivirales, expectorantes e inmunoestimulantes. Utilizada en la fitoterapia europea para infecciones respiratorias (bronquitis aguda) e infecciones urinarias, con aprobación de la Comisión E alemana para tales indicaciones. Las hojas y flores son comestibles y se usan en gastronomía como sustituto de la alcaparra y en ensaladas nutritivas. La tintura de la planta fresca muestra actividad antimicrobiana comparable a algunos antibióticos convencionales en infecciones urinarias.'),
(285,'it','Il nasturzio (Tropaeolum majus) è una pianta rampicante o strisciante annuale della famiglia delle Tropaeolacee, originaria delle regioni montane del Sud America. Le sue foglie, fiori e semi contengono glucosinolati (glucotropaeolina), isotiocianati (benzil-ITC), quercetina e vitamina C con proprietà antibatteriche, antivirali, espettoranti e immunostimolanti. Impiegato nella fitoterapia europea per infezioni respiratorie (bronchite acuta) e infezioni urinarie, con approvazione della Commissione E tedesca per tali indicazioni. Le foglie e i fiori sono commestibili e usati in gastronomia come sostituto del cappero e nelle insalate. La tintura della pianta fresca mostra attività antimicrobica paragonabile ad alcuni antibiotici nelle infezioni urinarie.'),
(285,'pt','O capuchinho ou chagas (Tropaeolum majus) é uma planta trepadeira ou rasteira anual da família Tropaeolaceae, originária das regiões montanhosas da América do Sul. As suas folhas, flores e sementes contêm glucosinolatos (glucotropaeolina), isotiocianatos (benzil-ITC), quercetina e vitamina C com propriedades antibacterianas, antivirais, expectorantes e imunoestimulantes. Utilizado na fitoterapia europeia para infeções respiratórias (bronquite aguda) e infeções urinárias, com aprovação da Comissão E alemã para tais indicações. As folhas e flores são comestíveis e usadas na gastronomia como substituto da alcaparra. A tintura da planta fresca mostra atividade antimicrobiana comparável a alguns antibióticos em infeções urinárias.'),
# ── Soapnuts [269] — es fr it pt
(269,'es','Las nueces de jabón (Sapindus mukorossi y S. saponaria) son frutos de la familia Sapindaceae, originarios de Asia tropical. Su pericarpios contienen saponinas triterpénicas (mukuroziosida) en concentraciones de hasta el 18%, que producen espuma biodegradable con propiedades tensioactivas, antibacterianas y antifúngicas. En la medicina ayurvédica se usan para tratar la psoriasis, la dermatitis, la caspa y las infestaciones de piojos, siendo también un champú natural para el cabello. La investigación moderna documenta actividad espermicida, antiparasitaria, antivírica y anticancerígena de los extractos de saponina. Son ampliamente promovidos como detergente ecológico y cosmético natural.'),
(269,'fr','Les noix de lavage (Sapindus mukorossi et S. saponaria) sont des fruits de la famille des Sapindacées, originaires d\'Asie tropicale. Leur péricarpe contient des saponines triterpéniques (mukuroziosides) à des concentrations pouvant atteindre 18%, produisant une mousse biodégradable aux propriétés tensioactives, antibactériennes et antifongiques. En médecine ayurvédique, elles sont utilisées pour traiter le psoriasis, la dermatite, les pellicules et les infestations de poux, servant également de shampoing naturel. Des recherches modernes documentent une activité spermicide, antiparasitaire, antivirale et anticancéreuse des extraits de saponine. Elles sont largement promues comme détergent écologique et cosmétique naturel.'),
(269,'it','Le noci da sapone (Sapindus mukorossi e S. saponaria) sono frutti della famiglia delle Sapindacee, originari dell\'Asia tropicale. Il loro pericarpo contiene saponine triterpeniche (mukuroziosidi) in concentrazioni fino al 18%, producendo schiuma biodegradabile con proprietà tensioattive, antibatteriche e antifungine. Nella medicina ayurvedica vengono usate per psoriasi, dermatite, forfora e infestazioni di pidocchi, fungendo anche da shampoo naturale. Ricerche moderne documentano attività spermicida, antiparassitaria, antivirale e anticancerosa degli estratti di saponina. Sono ampiamente promosse come detersivo ecologico e cosmetico naturale.'),
(269,'pt','As nozes de sabão (Sapindus mukorossi e S. saponaria) são frutos da família Sapindaceae, originários da Ásia tropical. O seu pericarpo contém saponinas triterpénicas (mukuroziosídeos) em concentrações de até 18%, produzindo espuma biodegradável com propriedades tensoativas, antibacterianas e antifúngicas. Na medicina ayurvédica são utilizadas para tratar psoríase, dermatite, caspa e infestações de piolhos, servindo também como champô natural. Investigações modernas documentam atividade espermicida, antiparasitária, antiviral e anticancerígena dos extratos de saponina. São amplamente promovidas como detergente ecológico e cosmético natural.'),
# ── Bergenia [271] — es fr it pt
(271,'es','La bergenia (Bergenia crassifolia y B. cordifolia) es una planta perenne de la familia Saxifragaceae, nativa de Asia central, desde Afganistán hasta China y el Himalaya. Sus rizomas y hojas contienen arbutina, bergenina, taninos condensados e hidroquinonas con propiedades astringentes, antisépticas, antiinflamatorias y diuréticas. En la medicina ayurvédica y tibetana se utiliza para tratar cálculos renales, disuria, hemorragias, diarrea y afecciones de las vías respiratorias. El extracto de bergenia ha mostrado actividad inhibitoria frente a bacterias patógenas y propiedades hepatoprotectoras en modelos animales. Las hojas se usan en el Altái para preparar un té ("chagyrsky tea") con propiedades adaptógenas.'),
(271,'fr','La bergénie (Bergenia crassifolia et B. cordifolia) est une plante vivace de la famille des Saxifragacées, native d\'Asie centrale, de l\'Afghanistan à la Chine et à la région himalayenne. Ses rhizomes et feuilles contiennent de l\'arbutoside, de la bergénine, des tanins condensés et des hydroquinones aux propriétés astringentes, antiseptiques, anti-inflammatoires et diurétiques. Dans la médecine ayurvédique et tibétaine, elle est utilisée pour traiter les calculs rénaux, la dysurie, les hémorragies, la diarrhée et les affections des voies respiratoires. L\'extrait de bergénie a montré une activité inhibitrice contre les bactéries pathogènes et des propriétés hépatoprotectrices dans des modèles animaux. Les feuilles sont utilisées dans l\'Altaï pour préparer un thé ("chagyrsky tea") aux propriétés adaptogènes.'),
(271,'it','La bergenia (Bergenia crassifolia e B. cordifolia) è una pianta perenne della famiglia delle Sassifragacee, nativa dell\'Asia centrale, dall\'Afghanistan alla Cina e alla regione himalayana. I suoi rizomi e foglie contengono arbutosidi, bergenina, tannini condensati e idrochinoni con proprietà astringenti, antisettiche, antinfiammatorie e diuretiche. Nella medicina ayurvedica e tibetana è usata per calcoli renali, disuria, emorragie, diarrea e affezioni delle vie respiratorie. L\'estratto di bergenia ha mostrato attività inibitoria contro batteri patogeni e proprietà epatoprotettive in modelli animali. Le foglie vengono usate nell\'Altai per preparare un tè ("chagyrsky tea") con proprietà adattogene.'),
(271,'pt','A bergénia (Bergenia crassifolia e B. cordifolia) é uma planta perene da família Saxifragaceae, nativa da Ásia Central, do Afeganistão à China e região himalaia. Os seus rizomas e folhas contêm arbutosídeo, bergenina, taninos condensados e hidroquinonas com propriedades adstringentes, antissépticas, anti-inflamatórias e diuréticas. Na medicina ayurvédica e tibetana é utilizada para tratar cálculos renais, disúria, hemorragias, diarreia e afecções respiratórias. O extrato de bergénia mostrou atividade inibitória contra bactérias patogénicas e propriedades hepatoprotetoras em modelos animais. As folhas são usadas no Altai para preparar um chá ("chagyrsky tea") com propriedades adaptogénicas.'),
# ── Agrimony [857] — es fr it pt
(857,'es','La agrimonia (Agrimonia eupatoria) es una planta perenne de la familia Rosaceae, nativa de las regiones templadas del hemisferio norte. Sus partes aéreas contienen flavonoides (luteolina, apigenina), taninos condensados, cumarinas y triterpenos que ejercen efectos astringentes, antiinflamatorios, antiespasmódicos y hepatoprotectores. En la fitoterapia europea tradicional se emplea para el tratamiento de la diarrea, la gastritis, la colecistitis y las infecciones del tracto urinario. La Comisión E alemana aprueba su uso como gargarismo para la faringitis y para el apoyo digestivo leve. Investigaciones recientes confirman su actividad antioxidante, antimicrobiana e hipoglucemiante.'),
(857,'fr','L\'aigremoine (Agrimonia eupatoria) est une plante vivace de la famille des Rosacées, native des régions tempérées de l\'hémisphère nord. Ses parties aériennes contiennent des flavonoïdes (lutéoline, apigénine), des tanins condensés, des coumarines et des triterpènes aux effets astringents, anti-inflammatoires, antispasmodiques et hépatoprotecteurs. En phytothérapie européenne traditionnelle, elle est employée pour la diarrhée, la gastrite, la cholécystite et les infections des voies urinaires. La Commission E allemande approuve son usage en gargarisme pour la pharyngite et comme soutien digestif léger. Des recherches récentes confirment son activité antioxydante, antimicrobienne et hypoglycémiante.'),
(857,'it','L\'agrimonia (Agrimonia eupatoria) è una pianta perenne della famiglia delle Rosacee, nativa delle regioni temperate dell\'emisfero nord. Le sue parti aeree contengono flavonoidi (luteolina, apigenina), tannini condensati, cumarine e triterpeni con effetti astringenti, antinfiammatori, antispasmodici ed epatoprotettivi. Nella fitoterapia europea tradizionale viene impiegata per diarrea, gastrite, colecistite e infezioni delle vie urinarie. La Commissione E tedesca approva il suo uso come gargarismo per la faringite e come supporto digestivo lieve. Ricerche recenti confermano l\'attività antiossidante, antimicrobica e ipoglicemizzante.'),
(857,'pt','A agrimónia (Agrimonia eupatoria) é uma planta perene da família Rosaceae, nativa das regiões temperadas do hemisfério norte. As suas partes aéreas contêm flavonoides (luteolina, apigenina), taninos condensados, cumarinas e triterpenos com efeitos adstringentes, anti-inflamatórios, antiespasmódicos e hepatoprotetores. Na fitoterapia europeia tradicional é utilizada para diarreia, gastrite, colecistite e infeções do trato urinário. A Comissão E alemã aprova o seu uso como gargarejo para faringite e como suporte digestivo leve. Investigações recentes confirmam a sua atividade antioxidante, antimicrobiana e hipoglicemiante.'),
# ── Lady's Mantle [861] — es fr it pt
(861,'es','El manto de la Virgen o alquimila (Alchemilla mollis y A. vulgaris) es una planta perenne de la familia Rosaceae, ampliamente distribuida en regiones templadas del hemisferio norte. Sus hojas y tallos contienen taninos condensados (pedunculagina), flavonoides (quercetina, kaempferol) y salicilatos con propiedades astringentes, antiinflamatorias, hemostáticas y antiespasmódicas. En la fitoterapia europea se usa especialmente en los trastornos menstruales: menorragia, dismenorrea, síndrome premenstrual, y como apoyo en la menopausia. Externamente se aplica en heridas, úlceras cutáneas e inflamaciones genitales. Investigaciones modernas confirman sus propiedades antimicrobianas, antioxidantes y cicatrizantes.'),
(861,'fr','Le manteau de Notre-Dame ou alchémille (Alchemilla mollis et A. vulgaris) est une plante vivace de la famille des Rosacées, largement répandue dans les régions tempérées de l\'hémisphère nord. Ses feuilles et tiges contiennent des tanins condensés (pédunculagine), des flavonoïdes (quercétine, kaempférol) et des salicylates aux propriétés astringentes, anti-inflammatoires, hémostatiques et antispasmodiques. En phytothérapie européenne, elle est particulièrement utilisée pour les troubles menstruels : ménorragie, dysménorrhée, syndrome prémenstruel et soutien à la ménopause. En usage externe, elle s\'applique sur les plaies, les ulcères cutanés et les inflammations génitales. Des recherches modernes confirment ses propriétés antimicrobiennes, antioxydantes et cicatrisantes.'),
(861,'it','Il mantello della Madonna o alchemilla (Alchemilla mollis e A. vulgaris) è una pianta perenne della famiglia delle Rosacee, ampiamente diffusa nelle regioni temperate dell\'emisfero nord. Le sue foglie e steli contengono tannini condensati (pedunculagina), flavonoidi (quercetina, kaempferolo) e salicilati con proprietà astringenti, antinfiammatorie, emostatiche e antispasmodiche. In fitoterapia europea è particolarmente usata per disturbi mestruali: menorragia, dismenorrea, sindrome premestruale e supporto alla menopausa. Esternamente si applica su ferite, ulcere cutanee e infiammazioni genitali. Ricerche moderne confermano proprietà antimicrobiche, antiossidanti e cicatrizzanti.'),
(861,'pt','O manto-de-nossa-senhora ou alquimila (Alchemilla mollis e A. vulgaris) é uma planta perene da família Rosaceae, amplamente distribuída nas regiões temperadas do hemisfério norte. As suas folhas e caules contêm taninos condensados (pedunculagina), flavonoides (quercetina, kaempferol) e salicilatos com propriedades adstringentes, anti-inflamatórias, hemostáticas e antiespasmódicas. Na fitoterapia europeia é especialmente utilizada para perturbações menstruais: menorragia, dismenorreia, síndrome pré-menstrual e suporte na menopausa. Externamente aplica-se em feridas, úlceras cutâneas e inflamações genitais. Investigações modernas confirmam propriedades antimicrobianas, antioxidantes e cicatrizantes.'),
# ── Tormentil [881] — es fr it pt
(881,'es','La tormentila (Potentilla erecta, sin. Tormentilla erecta) es una planta perenne de la familia Rosaceae, nativa de Europa y Asia occidental. Sus rizomas contienen taninos condensados (procianidinas, catequinas) en concentraciones de hasta el 20%, el mayor contenido de taninos conocido en plantas medicinales europeas. Empleada desde la Edad Media para el tratamiento de la diarrea, la disentería, la gastroenteritis, las úlceras orales y las hemorragias menores. El extracto de tormentila está aprobado por la Comisión E alemana para el tratamiento de la diarrea no específica y como enjuague bucal para inflamaciones orales y faríngeas. Investigaciones modernas confirman su potente actividad antiviral y antimicrobiana.'),
(881,'fr','La tormentille (Potentilla erecta, syn. Tormentilla erecta) est une plante vivace de la famille des Rosacées, native d\'Europe et d\'Asie occidentale. Ses rhizomes contiennent des tanins condensés (procyanidines, catéchines) en concentrations allant jusqu\'à 20%, la plus forte teneur en tanins connue chez les plantes médicinales européennes. Utilisée depuis le Moyen Âge pour traiter la diarrhée, la dysenterie, la gastroentérite, les ulcères buccaux et les hémorragies mineures. L\'extrait de tormentille est approuvé par la Commission E allemande pour le traitement de la diarrhée non spécifique et comme bain de bouche pour les inflammations orales et pharyngées. Des recherches modernes confirment son activité antivirale et antimicrobienne puissante.'),
(881,'it','La tormentilla (Potentilla erecta, sin. Tormentilla erecta) è una pianta perenne della famiglia delle Rosacee, nativa di Europa e Asia occidentale. I suoi rizomi contengono tannini condensati (procianidine, catechine) in concentrazioni fino al 20%, il più alto contenuto di tannini noto nelle piante medicinali europee. Impiegata fin dal Medioevo per diarrea, dissenteria, gastroenterite, ulcere orali ed emorragie minori. L\'estratto di tormentilla è approvato dalla Commissione E tedesca per il trattamento della diarrea aspecifica e come collutorio per infiammazioni orali e faringee. Ricerche moderne confermano la potente attività antivirale e antimicrobica.'),
(881,'pt','A tormentila (Potentilla erecta, sin. Tormentilla erecta) é uma planta perene da família Rosaceae, nativa da Europa e Ásia Ocidental. Os seus rizomas contêm taninos condensados (procianidinas, catequinas) em concentrações de até 20%, o maior teor de taninos conhecido em plantas medicinais europeias. Utilizada desde a Idade Média para o tratamento de diarreia, disenteria, gastroenterite, úlceras orais e hemorragias menores. O extrato de tormentila está aprovado pela Comissão E alemã para o tratamento da diarreia inespecífica e como colutório para inflamações orais e faríngeas. Investigações modernas confirmam a sua potente atividade antiviral e antimicrobiana.'),
# ── Monkshood [914] — es fr it pt
(914,'es','El acónito o matalobos (Aconitum napellus) es una planta perenne de la familia Ranunculaceae, nativa de las regiones montañosas de Europa y Asia occidental. Contiene alcaloides diterpénicos altamente tóxicos (aconitina, mesaconitina, hipaconitina) que actúan sobre los canales de sodio, provocando efectos analgésicos, antipiréticos y cardiotóxicos. Es una de las plantas más venenosas de Europa, siendo letal en dosis pequeñas; históricamente se usó como veneno de flecha. En dosis estrictamente controladas, la medicina tradicional china y ayurvédica utilizan preparaciones detoxificadas de acónito para el dolor severo, la artritis y las enfermedades reumáticas. La aconitina es objeto de investigación farmacológica por su actividad analgésica y potencial anticancerígeno.'),
(914,'fr','L\'aconit ou casque de Jupiter (Aconitum napellus) est une plante vivace de la famille des Renonculacées, native des régions montagneuses d\'Europe et d\'Asie occidentale. Il contient des alcaloïdes diterpéniques hautement toxiques (aconitine, mésaconitine, hypaconitine) qui agissent sur les canaux sodiques, provoquant des effets analgésiques, antipyrétiques et cardiotoxiques. C\'est l\'une des plantes les plus venimeuses d\'Europe, létale à faibles doses ; il fut historiquement utilisé comme poison de flèche. À des doses strictement contrôlées, la médecine traditionnelle chinoise et ayurvédique utilisent des préparations détoxifiées d\'aconit pour la douleur sévère, l\'arthrite et les maladies rhumatismales. L\'aconitine fait l\'objet de recherches pharmacologiques pour son activité analgésique et son potentiel anticancéreux.'),
(914,'it','L\'aconito o monachino (Aconitum napellus) è una pianta perenne della famiglia delle Ranuncolacee, nativa delle regioni montane d\'Europa e Asia occidentale. Contiene alcaloidi diterpenici altamente tossici (aconitina, mesaconitina, ipaconitina) che agiscono sui canali del sodio, causando effetti analgesici, antipiretici e cardiotossici. È una delle piante più velenose d\'Europa, letale a basse dosi; storicamente usata come veleno per frecce. A dosi strettamente controllate, la medicina tradizionale cinese e ayurvedica utilizza preparazioni detossificate di aconito per dolori severi, artrite e malattie reumatiche. L\'aconitina è oggetto di ricerca farmacologica per la sua attività analgesica e il potenziale anticanceroso.'),
(914,'pt','O acónito ou capacete-de-monge (Aconitum napellus) é uma planta perene da família Ranunculaceae, nativa das regiões montanhosas da Europa e Ásia Ocidental. Contém alcaloides diterpénicos altamente tóxicos (aconitina, mesaconitina, hipaconitina) que atuam nos canais de sódio, causando efeitos analgésicos, antipiréticos e cardiotóxicos. É uma das plantas mais venenosas da Europa, letal em pequenas doses; historicamente utilizada como veneno de flecha. Em doses estritamente controladas, a medicina tradicional chinesa e ayurvédica utilizam preparações desintoxicadas de acónito para a dor severa, artrite e doenças reumáticas. A aconitina é objeto de investigação farmacológica pela sua atividade analgésica e potencial anticancerígeno.'),
# ── Datura [954] — es fr it pt
(954,'es','La datura o estramonio (Datura stramonium y D. metel) es un género de plantas de la familia Solanaceae, que contiene alcaloides tropánicos altamente tóxicos: atropina, escopolamina (hioscina) e hiosciamina. Es una planta venenosa y alucinógena que ha sido utilizada con fines medicinales en la medicina ayurvédica, china, azteca e indígena americana para tratar el asma, el reumatismo, el dolor y los espasmos musculares. La escopolamina derivada de Datura es un fármaco moderno usado para náuseas, mareos del movimiento y sedación preoperatoria. El mal uso resulta en delirio, taquicardia, coma y muerte; su uso sin supervisión médica es extremadamente peligroso. Los extractos son investigados para propiedades anticolinérgicas y como agentes neurológicos de investigación.'),
(954,'fr','La datura ou stramoine (Datura stramonium et D. metel) est un genre de plantes de la famille des Solanacées, contenant des alcaloïdes tropaniques hautement toxiques : atropine, scopolamine (hyoscine) et hyoscyamine. C\'est une plante vénéneuse et hallucinogène utilisée à des fins médicinales dans la médecine ayurvédique, chinoise, aztèque et amérindienne pour traiter l\'asthme, les rhumatismes, les douleurs et les spasmes musculaires. La scopolamine dérivée du datura est un médicament moderne utilisé pour les nausées, le mal des transports et la sédation préopératoire. Le mauvais usage entraîne délire, tachycardie, coma et mort ; son utilisation sans supervision médicale est extrêmement dangereuse. Les extraits sont étudiés pour les propriétés anticholinergiques et comme agents neurologiques de recherche.'),
(954,'it','La datura o stramonio (Datura stramonium e D. metel) è un genere di piante della famiglia delle Solanacee, contenenti alcaloidi tropanichi altamente tossici: atropina, scopolamina (ioscina) e iosciamina. È una pianta velenosa e allucinogena impiegata a scopo medicinale nella medicina ayurvedica, cinese, azteca e dei nativi americani per asma, reumatismi, dolori e spasmi muscolari. La scopolamina derivata dalla datura è un farmaco moderno usato per nausea, cinetosi e sedazione preoperatoria. L\'uso improprio porta a delirio, tachicardia, coma e morte; il suo utilizzo senza supervisione medica è estremamente pericoloso. Gli estratti sono studiati per proprietà anticolinergiche e come agenti neurologici di ricerca.'),
(954,'pt','A datura ou estramônio (Datura stramonium e D. metel) é um género de plantas da família Solanaceae, contendo alcaloides tropânicos altamente tóxicos: atropina, escopolamina (hioscina) e hiosciamina. É uma planta venenosa e alucinogénica utilizada com fins medicinais na medicina ayurvédica, chinesa, asteca e indígena americana para tratar asma, reumatismo, dor e espasmos musculares. A escopolamina derivada da datura é um fármaco moderno utilizado para náuseas, enjoo de movimento e sedação pré-operatória. O uso indevido resulta em delírio, taquicardia, coma e morte; a sua utilização sem supervisão médica é extremamente perigosa. Os extratos são investigados pelas propriedades anticolinérgicas e como agentes neurológicos de investigação.'),
# ── Desmodium [907] — es fr it pt
(907,'es','El desmodio (Desmodium adscendens y D. gangeticum) es un género de la familia Fabaceae ampliamente distribuido en regiones tropicales. Sus hojas y tallos contienen salsosida, triptaminas, alcaloides beta-carbolínicos e isoflavonas con propiedades broncoespasmolíticas, antiinflamatorias, hepatoprotectoras y antifúngicas. D. adscendens es usado en la medicina tradicional africana para el asma, la epilepsia y el dolor abdominal, con ensayos clínicos que confirman su eficacia en el asma bronquial mediante la inhibición de la liberación de leucotrienos. D. gangeticum es una importante planta ayurvédica (shalaparni) para tonificar el organismo, tratar afecciones respiratorias y fiebres. La investigación moderna se centra en sus efectos broncodilatadores y neuroprotectores.'),
(907,'fr','Le desmodium (Desmodium adscendens et D. gangeticum) est un genre de la famille des Fabacées, largement répandu dans les régions tropicales. Ses feuilles et tiges contiennent des salsosides, des tryptamines, des alcaloïdes bêta-carboliniques et des isoflavones aux propriétés bronchospasmolytiques, anti-inflammatoires, hépatoprotectrices et antifongiques. D. adscendens est utilisé en médecine traditionnelle africaine pour l\'asthme, l\'épilepsie et les douleurs abdominales, avec des essais cliniques confirmant son efficacité dans l\'asthme bronchique par inhibition de la libération de leucotriènes. D. gangeticum est une importante plante ayurvédique (shalparni) pour tonifier l\'organisme et traiter les affections respiratoires et les fièvres. Des recherches modernes portent sur ses effets bronchodilatateurs et neuroprotecteurs.'),
(907,'it','Il desmodio (Desmodium adscendens e D. gangeticum) è un genere della famiglia delle Fabacee, ampiamente distribuito nelle regioni tropicali. Le sue foglie e steli contengono salsosidi, triptamine, alcaloidi beta-carbolinici e isoflavoni con proprietà broncoespasmolitiche, antinfiammatorie, epatoprotettive e antifungine. D. adscendens è usato nella medicina tradizionale africana per asma, epilessia e dolori addominali, con trial clinici che confermano l\'efficacia nell\'asma bronchiale tramite inibizione della liberazione di leucotrieni. D. gangeticum è un\'importante pianta ayurvedica (shalparni) per tonico generale, affezioni respiratorie e febbre. La ricerca moderna si concentra sugli effetti broncodilatatori e neuroprotettori.'),
(907,'pt','O desmodium (Desmodium adscendens e D. gangeticum) é um género da família Fabaceae amplamente distribuído nas regiões tropicais. As suas folhas e caules contêm salsosídeos, triptaminas, alcaloides beta-carbolínicos e isoflavonas com propriedades broncoespasmolíticas, anti-inflamatórias, hepatoprotetoras e antifúngicas. D. adscendens é utilizado na medicina tradicional africana para asma, epilepsia e dores abdominais, com ensaios clínicos confirmando a sua eficácia na asma brônquica por inibição da libertação de leucotrienos. D. gangeticum é uma importante planta ayurvédica (shalparni) para tonificar o organismo e tratar afecções respiratórias e febres. A investigação moderna foca-se nos efeitos broncodilatadores e neuroprotetores.'),
# ── Coral Tree [909] — es fr it pt
(909,'es','El árbol del coral (Erythrina variegata y E. crista-galli) es un género de la familia Fabaceae, distribuido en regiones tropicales y subtropicales de todo el mundo. Su corteza, semillas y hojas contienen alcaloides eritrinínicos (eritralina, eritramina, hipaforiina) con potentes propiedades calmantes, relajantes musculares y analgésicas. En la medicina tradicional latinoamericana, africana y asiática se usa para el insomnio, la ansiedad, el dolor reumático, la epilepsia y las infecciones de la piel. Los alcaloides de Erythrina actúan como agonistas de receptores GABA y bloqueantes de receptores de nicotina, explicando sus efectos neuroactivos. La investigación moderna explora sus potenciales aplicaciones en enfermedades neurológicas y como agentes antiinflamatorios.'),
(909,'fr','L\'érythrine ou arbre corail (Erythrina variegata et E. crista-galli) est un genre de la famille des Fabacées, répandu dans les régions tropicales et subtropicales du monde entier. Son écorce, ses graines et ses feuilles contiennent des alcaloïdes érythriniques (érythraline, érythramine, hypaphorine) aux puissantes propriétés calmantes, relaxantes musculaires et analgésiques. Dans la médecine traditionnelle latino-américaine, africaine et asiatique, il est utilisé pour l\'insomnie, l\'anxiété, les douleurs rhumatismales, l\'épilepsie et les infections cutanées. Les alcaloïdes d\'Erythrina agissent comme agonistes des récepteurs GABA et antagonistes des récepteurs nicotiniques, expliquant leurs effets neuroactifs. La recherche moderne explore leurs applications potentielles dans les maladies neurologiques et comme agents anti-inflammatoires.'),
(909,'it','L\'eritrina o albero del corallo (Erythrina variegata ed E. crista-galli) è un genere della famiglia delle Fabacee, diffuso nelle regioni tropicali e subtropicali di tutto il mondo. La sua corteccia, semi e foglie contengono alcaloidi eritrinici (eritralina, eritramina, ipaforiina) con potenti proprietà calmanti, miorilassanti e analgesiche. Nella medicina tradizionale latinoamericana, africana e asiatica è usato per insonnia, ansia, dolori reumatici, epilessia e infezioni cutanee. Gli alcaloidi di Erythrina agiscono come agonisti dei recettori GABA e antagonisti dei recettori nicotinici, spiegando i loro effetti neuroattivi. La ricerca moderna esplora potenziali applicazioni in malattie neurologiche e come agenti antinfiammatori.'),
(909,'pt','A eritrina ou árvore do coral (Erythrina variegata e E. crista-galli) é um género da família Fabaceae, distribuído pelas regiões tropicais e subtropicais de todo o mundo. A sua casca, sementes e folhas contêm alcaloides eritrínicos (eritralina, eritramina, hipaforiina) com potentes propriedades calmantes, relaxantes musculares e analgésicas. Na medicina tradicional latino-americana, africana e asiática é utilizada para insónia, ansiedade, dores reumáticas, epilepsia e infeções cutâneas. Os alcaloides de Erythrina atuam como agonistas dos receptores GABA e antagonistas dos receptores de nicotina, explicando os seus efeitos neuroativos. A investigação moderna explora potenciais aplicações em doenças neurológicas e como agentes anti-inflamatórios.'),
# ── Ground Cherry [965] — es fr it pt
(965,'es','El capulín o alquequenje (Physalis alkekengi y P. peruviana) es una planta de la familia Solanaceae, nativa de regiones templadas y tropicales del hemisferio norte. Sus frutos y cálices contienen witanólidos, fisalinas, flavonoides, vitamina C y ácido cítrico con propiedades antioxidantes, antiinflamatorias, inmunomoduladoras y antivirales. En la medicina ayurvédica y china se utiliza el fruto seco para tratar afecciones renales, artritis gotosa, ictericia y fiebre. Las fisalinas de P. peruviana han mostrado actividad antiparasitaria, antiinflamatoria e inmunosupresora en modelos de investigación. La uchuva (P. peruviana) se consume ampliamente como superfruto en Latinoamérica por su alto contenido en vitaminas y antioxidantes.'),
(965,'fr','Le coqueret ou alkékenge (Physalis alkekengi et P. peruviana) est une plante de la famille des Solanacées, native des régions tempérées et tropicales de l\'hémisphère nord. Ses fruits et calices contiennent des withanolides, des physalines, des flavonoïdes, de la vitamine C et de l\'acide citrique aux propriétés antioxydantes, anti-inflammatoires, immunomodulatrices et antivirales. Dans la médecine ayurvédique et chinoise, le fruit séché est utilisé pour traiter les affections rénales, la goutte, la jaunisse et la fièvre. Les physalines de P. peruviana ont montré une activité antiparasitaire, anti-inflammatoire et immunosuppressive dans des modèles de recherche. L\'uchuva (P. peruviana) est largement consommée comme super-fruit en Amérique latine pour sa richesse en vitamines et antioxydants.'),
(965,'it','Il capusello o fisalis (Physalis alkekengi e P. peruviana) è una pianta della famiglia delle Solanacee, nativa delle regioni temperate e tropicali dell\'emisfero nord. I suoi frutti e calici contengono witanolidi, fisaline, flavonoidi, vitamina C e acido citrico con proprietà antiossidanti, antinfiammatorie, immunomodulatrici e antivirali. Nella medicina ayurvedica e cinese il frutto essiccato viene usato per affezioni renali, artrite gottosa, itterizia e febbre. Le fisaline di P. peruviana hanno mostrato attività antiparassitaria, antinfiammatoria e immunosoppressiva in modelli di ricerca. L\'uchuva (P. peruviana) è ampiamente consumata come superfood in America Latina per l\'alto contenuto di vitamine e antiossidanti.'),
(965,'pt','O fisális ou alquequenque (Physalis alkekengi e P. peruviana) é uma planta da família Solanaceae, nativa das regiões temperadas e tropicais do hemisfério norte. Os seus frutos e cálices contêm witanolídeos, fisalinas, flavonoides, vitamina C e ácido cítrico com propriedades antioxidantes, anti-inflamatórias, imunomoduladoras e antivirais. Na medicina ayurvédica e chinesa o fruto seco é utilizado para afecções renais, artrite gotosa, icterícia e febre. As fisalinas de P. peruviana demonstraram atividade antiparasitária, anti-inflamatória e imunossupressora em modelos de investigação. A uchuva (P. peruviana) é amplamente consumida como superfrutas na América Latina pelo seu alto teor em vitaminas e antioxidantes.'),
]

conn = sqlite3.connect(DB)
conn.execute('PRAGMA encoding = "UTF-8"')
conn.text_factory = lambda b: b.decode('utf-8', errors='replace')
cur = conn.cursor()

n = 0
for pid, lang, text in FIXES:
    cur.execute(f'UPDATE museum_item SET description_{lang}=? WHERE id=?', (text, pid))
    print(f'[{pid}] {lang} ✓')
    n += 1

conn.commit()
conn.close()
print(f'\nTotal: {n}')
